[build]
builder = "nixpacks"

[deploy]
startCommand = "node simple-server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "5000"
